name: iris-training
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        env:
          REPO_TOKEN: ${{ secrets.CML_TOKEN }}
      - run: |
          pip install -r requirements.txt
          python iris_model.py
      - name: create-report
        env:
           REPO_TOKEN: ${{ secrets.CML_TOKEN }}
        run: |
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          cml comment create report.md
       
