name: iris-ci-cd
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        env:
          CML_TOKEN: ${{ secrets.CML_TOKEN }} # Update the environment variable name
      - run: |
          pip install -r requirements.txt
          python iris_model.py
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          cml-send-comment report.md
       
